In [141]:
import pandas as pd

In [142]:
begin_date = "2023-01-01"
end_date = "2024-12-31" 

date_df = pd.DataFrame({'Date':pd.date_range(start=begin_date, end=end_date)})

date_df['Day'] = date_df['Date'].dt.day
date_df['Month'] = date_df['Date'].dt.month
date_df['MonthName'] = date_df['Date'].dt.month_name()
date_df['Year'] = date_df['Date'].dt.year
date_df['DayOfWeek'] = date_df['Date'].dt.dayofweek
date_df['DayOfWeekName'] = date_df['Date'].dt.day_name()

In [143]:
holidays_df = pd.concat(map(pd.read_csv, ['raw_data/holidays/2023.csv', 'raw_data/holidays/2024.csv']))
holidays_df = holidays_df.rename(columns={'Name': 'HolidayName'})

In [144]:
holidays_df['Date'] = pd.to_datetime(holidays_df['Date'])

In [145]:
df = pd.merge(left=date_df, right=holidays_df, on=["Date"], how="left")

In [146]:
df

,Date,Day,Month,MonthName,Year,DayOfWeek,DayOfWeekName,HolidayName
0,2023-01-01,1,1,January,2023,6,Sunday,NaN
1,2023-01-02,2,1,January,2023,0,Monday,New Year's Day
2,2023-01-03,3,1,January,2023,1,Tuesday,NaN
3,2023-01-04,4,1,January,2023,2,Wednesday,NaN
4,2023-01-05,5,1,January,2023,3,Thursday,NaN
...,...,...,...,...,...,...,...,...
726,2024-12-27,27,12,December,2024,4,Friday,NaN
727,2024-12-28,28,12,December,2024,5,Saturday,NaN
728,2024-12-29,29,12,December,2024,6,Sunday,NaN
729,2024-12-30,30,12,December,2024,0,Monday,NaN
730,2024-12-31,31,12,December,2024,1,Tuesday,NaN